services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka:
    image: docker.io/bitnami/kafka:3.8.1
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-net
  
  kafka-init:
    image: docker.io/bitnami/kafka:3.8.1
    container_name: kafka-init
    command: ["/bin/bash", "-c", "/create-topic.sh"]
    environment:
      - INPUT_TOPIC_NAME=raw_tweets
      - OUTPUT_TOPIC_NAME=processed_tweets
      - PARTITIONS=1
      - REPLICATION_FACTOR=1
    depends_on:
      - kafka
    volumes:
      - type: bind
        source: ./scripts/create-topic.sh
        target: /create-topic.sh
    networks:
      - kafka-net
  
  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./metrics/prometheus.yml:/etc/prometheus/prometheus.yml"
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./metrics/grafana:/etc/grafana/provisioning"

networks:
  kafka-net:
    driver: bridge