{
 "title": "Tweet Ingestor",
 "description": "Metrics for the Tweet Ingestor component",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregationInterval", "label": "Aggregation window", "query": "1m, 2m, 5m, 10m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time since the Tweet Ingestor service started",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"tweet-ingestor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/\", job=\"tweet-ingestor\"}[$aggregationInterval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Failed requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/\", job=\"tweet-ingestor\", status=~\"5xx|4xx\"}[$aggregationInterval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}